POST https://api.trafikinfo.trafikverket.se/v2/data.json HTTP/1.1
content-type: application/xml

<REQUEST>
  <LOGIN authenticationkey="demokey" />
  <QUERY objecttype="Situation" namespace="road.trafficinfo" schemaversion="1.6" limit="10">
	<FILTER>
      <AND>
        <EQ name="CountryCode" value="SE" />
		<EQ name="Deleted" value="false" />
		<!--EQ name="Deviation.Suspended" value="false" /-->
        <!--IN name="Deviation.CountyNo" value="{{trafikverketCountyNos}}" /-->
        <IN name="Deviation.CountyNo" value="12" />
		<GTE name="Deviation.SeverityCode" value="5" />
		<IN name="Deviation.MessageCode" value="Beläggningsarbete,Vägarbete" />
      </AND>
    </FILTER>
    <INCLUDE>PublicationTime</INCLUDE>
	<INCLUDE>ModifiedTime</INCLUDE>
    <INCLUDE>Deviation.Creator</INCLUDE>
	<INCLUDE>Deviation.StartTime</INCLUDE>
	<INCLUDE>Deviation.EndTime</INCLUDE>
    <INCLUDE>Deviation.Schedule.StartOfPeriod</INCLUDE>
	<INCLUDE>Deviation.Schedule.EndOfPeriod</INCLUDE>
    <INCLUDE>Deviation.Header</INCLUDE>
	<INCLUDE>Deviation.MessageCode</INCLUDE>
	<INCLUDE>Deviation.MessageType</INCLUDE>
    <INCLUDE>Deviation.Message</INCLUDE>
	<INCLUDE>Deviation.SeverityCode</INCLUDE>
    <INCLUDE>Deviation.SeverityText</INCLUDE>
    <INCLUDE>Deviation.LocationDescriptor</INCLUDE>
  </QUERY>
</REQUEST>